### PR TITLE
fix link for graph generation advanced workflow

### PR DESCRIPTION
**Pull request by ooker777**

### CODE REVIEW

**Comment by ooker777** [comment]
Why do you not think it's a good idea?

**Comment by Mara-Li** [comment]
Looks at the last commit please, you will understand.

**Comment by ooker777** [comment]
I see. Btw, when you say "please", do you feel annoyed or it's just a habit or a norm that you are in?

**Comment by Mara-Li** [comment]
I was a little annoyed but don't worry, I just don't have much sleep and sometimes, the gestion of this project is pretty overwhelming.
I don't want justify every action I take, but it's more because I have the habit to work alone.

So don't worry, your PR was added manually when I edited the file. At this moment, I don't want to deal with merging PR for just a line!

**Comment by ooker777** [comment]
I understand, an FOSS demands a lot of work to have it functional, while returns basically nothing. The tools are not natural to our cognitive functions. Gratitude from users doesn't really help your life less burdensome. I wish I could help you something, or at least be there so you don't feel lonely, but I can't.

**Pull request closed without merging**
